/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view.questions;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import abd.p1.model.Opcion;
import abd.p1.model.Pregunta;

/**
 *
 * @author labrador
 */
public class QuestionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionsPanel
     */
    public QuestionsPanel() {
        initComponents();

        Pregunta p1 = new Pregunta(0, "¿Te gusta fútbol?", new ArrayList<Opcion>());
        p1.getOpciones().add(new Opcion());
        p1.getOpciones().add(new Opcion());
        p1.getOpciones().add(new Opcion());
        Pregunta p2 = new Pregunta(1, "¿Te gusta viajar?", new ArrayList<Opcion>());
        p2.getOpciones().add(new Opcion());
        p2.getOpciones().add(new Opcion());
        Pregunta p3 = new Pregunta(2, "¿A qué partido no votarías nunca?", new ArrayList<Opcion>());
        p3.getOpciones().add(new Opcion());
        p3.getOpciones().add(new Opcion());
        p3.getOpciones().add(new Opcion());
        p3.getOpciones().add(new Opcion());

        DefaultListModel<Pregunta> modelo = new DefaultListModel<>();
        modelo.addElement(p1);
        modelo.addElement(p2);
        modelo.addElement(p3);

        questionsList.setModel(modelo);
        questionsList.setCellRenderer(new QuestionCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        answerButton = new javax.swing.JButton();
        randomAnswerButton = new javax.swing.JButton();
        labelFiltro = new javax.swing.JLabel();
        scrollPreguntas = new javax.swing.JScrollPane();
        questionsList = new javax.swing.JList<>();

        answerButton.setMnemonic('A');
        answerButton.setText("Responder");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });
        panelBotones.add(answerButton);

        randomAnswerButton.setMnemonic('E');
        randomAnswerButton.setText("Pregunta aleatoria");
        randomAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomAnswerButtonActionPerformed(evt);
            }
        });
        panelBotones.add(randomAnswerButton);

        labelFiltro.setDisplayedMnemonic('F');
        labelFiltro.setText("Mejor valoradas:");

        scrollPreguntas.setViewportView(questionsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPreguntas)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFiltro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void randomAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JList<Pregunta> questionsList;
    private javax.swing.JButton randomAnswerButton;
    private javax.swing.JScrollPane scrollPreguntas;
    // End of variables declaration//GEN-END:variables
}
